stages:
  - build
  - test

build_probe:
  stage: build
  variables:
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

  image: docker:24.0

  services:
    - docker:dind

  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

  script:
    - docker build -t $CONTAINER_RELEASE_IMAGE --build-arg GITLAB_TOKEN_USER=gitlab-ci-token --build-arg GITLAB_TOKEN=$CI_JOB_TOKEN .
    - docker push $CONTAINER_RELEASE_IMAGE

  interruptible: true

test_probe:
  stage: test
  image: docker:24.0

  services:
    - docker:dind

  script:
    - docker pull $CONTAINER_RELEASE_IMAGE
    - docker run $CONTAINER_RELEASE_IMAGE pytest